### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by csmetzner** [keknight/DSE_511_project3#1]

**Comment by annamarianau** [comment]
In progress, should be done soon.

**Comment by annamarianau** [comment]
The following preprocessing steps will be performed:
- Download and import the data from Kaggle.
- Basic data analysis tasks including missing values, unique values per column, outliers, etc.
- Dropping redundant and/or unnecessary columns.
- Split data into train and test sets (80:20 split).
- Min-max data normalization. 
- Principal component analysis (PCA) on normalized data for feature extraction.

After preprocessing the following train/test sets will be saved and used for modeling:
1. Normalized data: X_train_scaled, y_train_scaled, X_test_scaled, y_test_scaled
2. Normalized + PCA data: X_train_pca, y_train_pca, X_test_pca, y_test_pca

**Comment by annamarianau** [comment]
Code for this issue in data_preprocessing.py
