### ISSUE TITLE
'TabError' when executing src/feature_importance.py

### ISSUE THREAD

**Issue by annamarianau** [keknight/DSE_511_project3#10]
The following error occurs when src/feature_imprtance.py is executed:

<img width="845" alt="Screen Shot 2021-11-28 at 1 35 21 PM" src="https://user-images.githubusercontent.com/31635688/143781349-ae0219a3-57f4-46d2-a3d8-2b809fadada0.png">

**Comment by keknight** [comment]
Just fixed the feature_importance.py errors, re-ran everything and it all works on my end, please let me know if you're still getting errors. If all's fine, close issue
