### ISSUE TITLE
Delete feature branches prior to project submission (Dec 9 by 11:59pm)

### ISSUE THREAD

**Issue by annamarianau** [keknight/DSE_511_project3#11]
Delete feature branches by Dec 9 by 11:59pm. Prior to doing so, merge any necessary code to the main branch. 

To delete a branch both locally and remotely go [here](https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/) for help.

**Comment by csmetzner** [comment]
Completed - all branches are deleted!
